### ISSUE TITLE
DynArray Deletion Test Failing

### ISSUE THREAD

**Issue by GelbEinhalb** [GymnasiumEverstenOldenburg/KCImplementations#1]
DynArray Test `testDelete()` is failing.

```java
java.lang.IllegalArgumentException: Ungültiger Index!

	at main.java.DynArray.getItemClass(DynArray.java:60)
	at main.java.DynArray.delete(DynArray.java:151)
	...

Process finished with exit code -1
```

**Comment by GelbEinhalb** [comment]
`src/main/java/DynArray.java`
```java
/**
 * Das Element an der Position index wird entfernt. Alle folgenden Elemente
 * werden um eine Position
 * nach vorne geschoben.
 *
 * @param index Der Index an dem das Element gelöscht werden soll.
 */
public void delete(int index) {
    Item<Type> previous = getItemClass(index - 1);
    Item<Type> current = previous.getNext();
    Item<Type> next = current.getNext();
    previous.setNext(next);
}
```

@Alexander-Reimer 
Wenn das DynArray leer ist, kann in `delete()` nicht mehr das `previous` Element bekommen und unsere `getItemClass()` Methode wirft `IllegalArgumentException("Ungültiger Index!");`
